from typing import Any


class Error(Exception): ...
class HttpError(Error):
    resp: Any
    content: bytes
    url: str
    error_details: str
    def __init__(self, resp: Any, content: bytes, *, uri: str | None = ...) -> None: ...
    @property
    def status_code(self) -> int: ...
class InvalidJsonError(Error): ...
class UnknownFileType(Error): ...
class UnknownLinkType(Error): ...
class UnknownApiNameOrVersion(Error): ...
class UnacceptableMimeTypeError(Error): ...
class MediaUploadSizeError(Error): ...
class ResumableUploadError(HttpError): ...
class InvalidChunkSizeError(Error): ...
class InvalidNotificationError(Error): ...
class BatchError(HttpError):
    def __init__(self, reason: str, *, resp: Any | None = ..., content: bytes | None = ...) -> None: ...
class UnexpectedMethodError(Error):
    def __init__(self, *, methodId: str | None = ...) -> None: ...
class UnexpectedBodyError(Error):
    def __init__(self, expected: str, provided: str) -> None: ...
