from typing import Any

from ..core import Stream

class TemplateError(Exception): ...

class DirectiveFactoryMeta(type): ...

class DirectiveFactory(metaclass=DirectiveFactoryMeta): ...

class Template(DirectiveFactory):
    def generate(self, **kwargs: Any) -> Stream: ...
