from ..util import ImmutableProperties, OrderedProperties
from .elements import ColumnElement

class Immutable: ...
class DialectKWArgs: ...
class Generative: ...
class Executable(Generative): ...
class SchemaEventTarget: ...

class ColumnCollection(OrderedProperties[ColumnElement]):
    def __init__(self, *columns: ColumnElement) -> None: ...

class ImmutableColumnCollection(ImmutableProperties, ColumnCollection): ...
