from typing import Any

from ..util import ImmutableProperties, OrderedProperties
from .elements import ColumnElement

class Immutable: ...
class DialectKWArgs: ...
class Generative: ...
class Executable(Generative): ...
class SchemaEventTarget: ...

class ColumnCollection(OrderedProperties[ColumnElement[Any]]):
    def __init__(self, *columns: ColumnElement[Any]) -> None: ...

class ImmutableColumnCollection(ImmutableProperties[ColumnElement[Any]], ColumnCollection): ...
