from typing import Union, TypeVar, Generic

from . import operators

_T = TypeVar("_T")


def not_(clause: Union[ClauseElement, None]) -> ClauseElement: ...

class ClauseElement: ...
class ColumnElement(operators.ColumnOperators[_T], ClauseElement, Generic[_T]): ...
class ColumnClause(ColumnElement[_T], Generic[_T]): ...

class ClauseList(ClauseElement): ...
class BooleanClauseList(ClauseList, ColumnElement[bool]): ...
