from typing import Union

from . import operators

def not_(clause: Union[ClauseElement, None]) -> ClauseElement: ...

class ClauseElement: ...
class ColumnElement(operators.ColumnOperators, ClauseElement): ...
class ColumnClause(ColumnElement): ...

class ClauseList(ClauseElement): ...
class BooleanClauseList(ClauseList, ColumnElement): ...
