from typing import Any, Optional

from .elements import BooleanClauseList, ClauseElement, TextClause

from .functions import (
    func as func,
)

def insert(table: Any, values: Optional[Any] = ...) -> Any: ...
def select(columns: Optional[Any] = ..., whereclause: Optional[ClauseElement] = ...) -> Any: ...

def desc(column: Any) -> Any: ...

def and_(*clauses: ClauseElement) -> BooleanClauseList: ...
def or_(*clauses: ClauseElement) -> BooleanClauseList: ...

def text(text: str) -> TextClause: ...
