from typing import Any, Optional


class _FunctionGenerator:
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __getattr__(self, item: str) -> _FunctionGenerator: ...

func: _FunctionGenerator

class GenericFunction: ...

class count(GenericFunction):
    def __init__(self, expression: Optional[Any] = ..., **kwargs: Any) -> None: ...
