from typing import Any, Optional


class ColumnOperators:
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
    def __gt__(self, other: Any) -> Any: ...
    def __ge__(self, other: Any) -> Any: ...
    def __lt__(self, other: Any) -> Any: ...
    def __le__(self, other: Any) -> Any: ...
    def any_(self) -> Any: ...
    def all_(self) -> Any: ...
    def desc(self) -> Any: ...
    def asc(self) -> Any: ...
    def in_(self, other: Any) -> Any: ...
    def is_(self, other: Any) -> Any: ...
    def isnot(self, other: Any) -> Any: ...
    def like(self, other: Any, escape: Optional[str] = ...) -> Any: ...
    def match(self, other: Any, **kwargs: Any) -> Any: ...
