import enum
from typing import Optional, overload, Type

from .base import SchemaEventTarget
from .type_api import TypeEngine, Emulated

class Boolean(TypeEngine): ...
class Date(TypeEngine): ...
class DateTime(TypeEngine): ...
class DATETIME(DateTime): ...
class Integer(TypeEngine): ...

class Numeric(TypeEngine):
    def __init__(
        self,
        precision: Optional[int] = ...,
        scale: Optional[int] = ...,
        decimal_return_scale: Optional[int] = ...,
        asdecimal: bool = ...,
    ) -> None: ...

class Float(Numeric): ...
class DECIMAL(Numeric): ...
class JSON(TypeEngine): ...

class String(TypeEngine):
    def __init__(self, length: Optional[int] = ...) -> None: ...
class Text(String): ...

class Time(TypeEngine): ...
class TIMESTAMP(DateTime): ...

class Unicode(String):
    def __init__(self, length: Optional[int] = ...) -> None: ...

class SchemaType(SchemaEventTarget): ...

class Enum(Emulated, String, SchemaType):
    @overload
    def __init__(self, enums: Type[enum.Enum]) -> None: ...
    @overload
    def __init__(self, *enums: str) -> None: ...
