from typing import Optional

from .type_api import TypeEngine


class Boolean(TypeEngine): ...
class Date(TypeEngine): ...
class DateTime(TypeEngine): ...
class Integer(TypeEngine): ...
class JSON(TypeEngine): ...

class String(TypeEngine):
    def __init__(self, length: Optional[int] = ...) -> None: ...

class Time(TypeEngine): ...
class TIMESTAMP(DateTime): ...

class Unicode(String):
    def __init__(self, length: Optional[int] = ...) -> None: ...
