from typing import Any

class AMQPObject(object):
    NAME: str = ...
    INDEX: None = ...

class Class(AMQPObject): ...

class Method(AMQPObject):
    synchronous: bool = ...
    # FIXME: Return type pika.frame.Properties
    def get_properties(self) -> Any: ...
    def get_body(self) -> bytes: ...

class Properties(AMQPObject): ...
