# incomplete

def to_unicode(obj: float | bytes | str, encoding: str | None = ..., from_server: bool = ...) -> str: ...

def escape_filter_chars(text: float | bytes | str, encoding: str | None = ...) -> str: ...
