from typing import Tuple, Optional

from ..utils.handlers import HasRounds, HasRawSalt, HasRawChecksum, GenericHandler

class Pbkdf2DigestHandler(HasRounds, HasRawSalt, HasRawChecksum, GenericHandler):
    setting_kwds: Tuple[str, str, str] = ...
    checksum_chars: str = ...
    default_salt_size: int = ...
    max_salt_size: int = ...
    default_rounds: Optional[int] = ...
    min_rounds: int = ...
    max_rounds: int = ...
    rounds_cost: str = ...
