from typing import Protocol, Any, Union

from .Worksheet import Worksheet

class _Writable(Protocol):
    def write(self, text: bytes) -> Any: ...
    def close(self) -> Any: ...

class Workbook:
    def __init__(self, encoding: str = ..., style_compression: int = ...) -> None: ...
    def add_sheet(self, sheetname: str, cell_overwrite_ok: bool = ...) -> Worksheet: ...
    def save(self, filename_or_stream: Union[str, bytes, int, _Writable]) -> None: ...
