from typing import TypeVar, Generic

_T = TypeVar("_T")

class ImmutableContainer: ...

class Properties(Generic[_T]):
    def __getattr__(self, key: str) -> _T: ...

class OrderedProperties(Properties[_T], Generic[_T]): ...
class ImmutableProperties(ImmutableContainer, Properties[_T], Generic[_T]): ...
