from typing import Any, List, Optional, Generic, TypeVar

_T = TypeVar("_T")

class Query(Generic[_T]):
    def all(self) -> List[_T]: ...
    def delete(self, synchronize_session: str = ...) -> int: ...
    def first(self) -> Optional[_T]: ...
    def filter(self, *criterion: Any) -> Query[_T]: ...
    def filter_by(self, **kwargs: Any) -> Query[_T]: ...
    def order_by(self, *criterion: Any) -> Query[_T]: ...
    def join(self, *props: Any) -> Query[_T]: ...
