from typing import Any

class HasDescriptionCode:
    code: str | None
    def __init__(self, *arg: Any, code: str | None = ..., **kw: Any) -> None: ...

class SQLAlchemyError(HasDescriptionCode, Exception): ...
class StatementError(SQLAlchemyError): ...
class DBAPIError(StatementError): ...
class DatabaseError(DBAPIError): ...
class DataError(DatabaseError): ...
class OperationalError(DatabaseError): ...
class IntegrityError(DatabaseError): ...

class SAWarning(HasDescriptionCode, RuntimeWarning): ...
